  /* This file generated by /home/forrest/Documents/linpack/ATLAS/intel_i7/..//tune/threads/probe_nthr.c */
#ifndef ATLAS_NTHREADS_H
   #define ATLAS_NTHREADS_H

#include "pthread.h"
   #define ATL_NTHREADS 8
   #define ATL_NTHRPOW2 3
   #ifdef ATL_LAUNCHORDER
       static int ATL_launchorder[8] = {0,4,2,6,1,5,3,7};
   #endif

#endif
